{
parserClass="camp.delta.deltatypetheory.plugin.parser.DeltaTypeTheoryParser"

elementTypeHolderClass="camp.delta.deltatypetheory.plugin.psi.DeltaTypeTheoryTypes"
elementTypeClass="camp.delta.deltatypetheory.plugin.psi.DeltaTypeTheoryElementType"
tokenTypeClass="camp.delta.deltatypetheory.plugin.psi.DeltaTypeTheoryTokenType"

psiClassPrefix="DeltaTypeTheory"
psiImplClassSuffix="Impl"
psiPackage="camp.delta.deltatypetheory.plugin.psi"
psiImplPackage="camp.delta.deltatypetheory.plugin.psi.impl"


tokens = [
    AXIOM_KEYWORD
    DEF_KEYWORD
    IDENTIFIER
    EQUAL
    TO
    FOLLOWS
    LAMBDA
    COLON
    LPAREN
    RPAREN
    SEMICOLON
]
}


deltaTypeTheoryFile ::= item*

item ::= axiomDecl | defDecl

axiomDecl ::= AXIOM_KEYWORD identifier COLON expr SEMICOLON

defDecl ::= DEF_KEYWORD identifier COLON expr EQUAL expr SEMICOLON

expr ::= lambdaExpr | piExpr | application | atom

lambdaExpr ::= LAMBDA LPAREN identifier COLON expr RPAREN FOLLOWS expr

piExpr ::= LPAREN identifier COLON expr RPAREN TO expr

application ::= atom argument+

argument ::= LPAREN expr RPAREN

atom ::= identifier | LPAREN expr RPAREN
